// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frbbnaxdzpqwavkkbngy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyYmJuYXhkenBxd2F2a2tibmd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NDEyNjgsImV4cCI6MjA3MTQxNzI2OH0.XU2OWdsIiZMy8Dn5jw9woAmy_7UkhnNJZYO4_kMAVi4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});